### ISSUE TITLE
Landing Page for BrowserToolbox

### ISSUE THREAD

**Issue by imabp** [the-browser-toolbox/docs#1]
@adityabisoi 
I saw the org projects, they are really elegant ones. Kudos.

I have a proposal, that can we have a single landing page up for Browser Tool Box.

The Landing page would be more of a minimal and elegant way.

I want to use this tech stack.
✅ ReactJS for Frontend.
 ❌ react-router-dom for routes.  ( Not needed for now, as this will be a completely single page )
Edit 

Hosting:
May be on Netlify.

Please let me know your view on this.

**Comment by adityabisoi** [comment]
@imabp So, your idea is to build a website to show the capabilities and features of the extension, right?

**Comment by imabp** [comment]
Yea, you get me right.

Kind of a simple minimalism style, Org Landing page.

**Comment by imabp** [comment]
@adityabisoi are we following some project board, to keep track of issues and updates ?

**Comment by adityabisoi** [comment]
@imabp Not right now, we are following those on the comm channel. We can do that, if we want.

**Comment by adityabisoi** [comment]
@imabp Go ahead.

**Comment by rachittshah** [comment]
Hey @adityabisoi @imabp , we can use Gatsby as well? 

Views?

**Comment by imabp** [comment]
@godslayer201,

 Actually, I have started the things with ReactJS and material UI and keeping it simple.. and minimalistic, locally.
Let's see the v1.0, with react, and then if we find any performance issues, we can head over to GatsByJS.

Edit: Let me know if that makes sense?

**Comment by rachittshah** [comment]
Amazing! Do let me know if you need a hand!

**Comment by imabp** [comment]
@godslayer201 @adityabisoi 
I have raised a PR #2  describing every change
Pls, let me know if you need more information.
